### ISSUE TITLE
Gunzipping a Folder

### ISSUE THREAD

**Issue by perlmunger** [1024jp/NSData-GZIP#1]
I wasn't sure from your README how I might use this to gunzip a folder of files in my Documents directory for example. Are you able to just call write on the NSData object and it will handle writing out all of the files in the archive?

Thanks.

**Comment by 1024jp** [comment]
In the first place, gzip cannot compress multiple files. You need first to archive your files into a single file using _Tar_ or something, and this extension has nothing to do with it. 

Sorry for my late answer. I hope you've already found your solution.
