### ISSUE TITLE
No such module 'zlib'

### ISSUE THREAD

**Issue by deermapper** [1024jp/NSData-GZIP#6]
It seems like adding libz.tbd to "Link Binary With Libraries" does not work in Xcode 7.0. zlib can not be found:

![bildschirmfoto 2015-09-23 um 11 27 23](https://cloud.githubusercontent.com/assets/6825724/10041713/623cb874-61e6-11e5-8911-3fd3deb3ed23.png)

Does anyone have an idea?

**Comment by jazzbox** [comment]
You have to set the correct path in SWIFT_INCLUDE_PATHS relative to your .xcodeproj file! The ../zlib in the README.md for example means that zlib is in the parent directory!

**Comment by deermapper** [comment]
Tried every possible setup.

This seems for me the most plausible one - but it does not work:

<img width="1119" alt="bildschirmfoto 2015-09-27 um 11 40 41" src="https://cloud.githubusercontent.com/assets/6825724/10122110/a1a78f92-650c-11e5-83a9-254cd90d9ac3.png">

**Comment by MrJanssen** [comment]
Same issue here..
Deleting 'import zlib' actually solved the problem.
I read somewhere once you include a header file you don't need to import it anymore.. [?]

**Comment by tsimmi** [comment]
I have the same issue.
Tried deleting the 'import zlib' but to no effect.
Can anyone shed some light on why this is happening?

**Comment by deermapper** [comment]
I had to adjust the Import Paths under Search Paths in Build Settings. The path has to be set correct relating to the document structure on the disc. Check the file structure by right clicking your Project Name  > Show in Finder. You find see there the folder containing your zlib folder. 
In my project, the zlib folder was in at the same level / folder as the *.xcodeproj file -> so the import path was just "zlib" (and not "./zlib" or "../zlib" , ...)

**Comment by tsimmi** [comment]
Yeah. That was it.
Thanks for the help!

**Comment by learnopengles** [comment]
I had a similar problem only when compiling for profiling, and only when compiling for the phone. I finally was able to fix it by wiping out everything in DerivedData.
